import { env } from '$env/dynamic/private';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';

import { applicationSetup, knownDevices, telemetrySamples } from './generated/schema';

import {
	account,
	accountRelations,
	session,
	sessionRelations,
	user,
	userRelations,
	verification
} from './generated/auth.schema';

if (!env.DATABASE_URL) {
	throw new Error('DATABASE_URL is not set');
}

const client = postgres(env.DATABASE_URL);

export const schema = {
	// Application tables generated by drizzle-kit pull.
	applicationSetup,
	knownDevices,
	telemetrySamples,

	// Better Auth tables generated by Better Auth.
	user,
	session,
	account,
	verification,

	// Better Auth relations.
	userRelations,
	sessionRelations,
	accountRelations
};

export const db = drizzle(client, { schema });
